'use client';

import { useEffect, useState } from 'react';
import { doc, getDoc } from 'firebase/firestore';
import { onAuthStateChanged } from 'firebase/auth';
import { useRouter } from 'next/navigation';
import { auth, db, firebaseConfigured } from '../../../lib/firebase';
import styles from './seo.module.css';

export default function SeoManagerPage() {
  const router = useRouter();
  const [allowed, setAllowed] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!firebaseConfigured || !auth || !db) { setLoading(false); return undefined; }
    return onAuthStateChanged(auth, async (user) => {
      if (!user) { router.replace('/admin/login'); return; }
      const snap = await getDoc(doc(db, 'admins', user.uid));
      if (!snap.exists() || snap.data()?.active !== true) { router.replace('/admin/login?error=unauthorized'); return; }
      setAllowed(true);
      setLoading(false);
    });
  }, [router]);

  if (loading) return <main className={styles.page}><div className={styles.card}>Checking SEO access…</div></main>;
  if (!allowed) return null;
  return (
    <main className={styles.page}>
      <div className={styles.topbar}>
        <div><span className={styles.kicker}>PHASE 3.11</span><h1>SEO & Search Setup</h1><p>Technical SEO is now part of the website build. This page lists the final deployment settings.</p></div>
        <button onClick={() => router.push('/admin/dashboard')}>← Dashboard</button>
      </div>
      <section className={styles.card}>
        <h2>Implemented automatically</h2>
        <div className={styles.grid}>
          <div><strong>Metadata</strong><span>Title, description, keywords, robots, Open Graph and Twitter sharing.</span></div>
          <div><strong>Sitemap</strong><span>/sitemap.xml is generated by Next.js.</span></div>
          <div><strong>Robots</strong><span>/robots.txt allows public pages and blocks admin/API paths.</span></div>
          <div><strong>Structured Data</strong><span>EducationalOrganization JSON-LD includes the coaching name, Champua/ Odisha location and all contact numbers.</span></div>
        </div>
        <h2>One Vercel setting</h2>
        <p>Add <code>NEXT_PUBLIC_SITE_URL</code> in Vercel → Settings → Environment Variables and set it to the exact public website URL. This improves canonical and sitemap URLs.</p>
      </section>
    </main>
  );
}
